# Generated by Django 4.2.26 on 2025-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_add_timestamps_and_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grade',
            new_name='grades_grad_created_b9a500_idx',
            old_name='grades_grad_created_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='grades_grad_updated_19e55e_idx',
            old_name='grades_grad_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='grades_grad_course__1cae01_idx',
            old_name='grades_grad_course_created_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeauditlog',
            new_name='grades_grad_accesse_de57ef_idx',
            old_name='grades_grad_accessed_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeauditlog',
            new_name='grades_grad_snapsho_c52c08_idx',
            old_name='grades_grad_snapshot_idx',
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when grade was first created (for MVCC/snapshot isolation)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when grade was last updated (for MVCC/snapshot isolation)'),
        ),
    ]
