# Generated by Django 4.2.26 on 2025-12-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student']},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'course'], name='courses_att_student_8d9604_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'date'], name='courses_att_course__1c47ee_idx'),
        ),
    ]
