# Generated by Django 4.2.26 on 2025-11-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course')),
            ],
            options={
                'unique_together': {('code', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ContributionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0, help_text='Percentage contribution (0-100)')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_rates', to='outcomes.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_rates', to='outcomes.programoutcome')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contributionrate',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='valid_percentage_range'),
        ),
        migrations.AlterUniqueTogether(
            name='contributionrate',
            unique_together={('learning_outcome', 'program_outcome')},
        ),
    ]
